### ISSUE TITLE
Add d.ts typing files into package

### ISSUE THREAD

**Issue by pashchuk** [paybyrd/card-collect-js#6]
Dear PayByrd team.

As your customers we often working with libraries you are providing to us. But there are some tech issues while working with them which is lack of typing files which properly describe the interface schema to work with the library.
Could you please add them in some of the recent releases, as adding them should be relatively simple as letting your bundler specific configuration entry to export typing files and include them into packages description.

You can also find the example of your own [threedsecure-service-js](https://github.com/paybyrd/threedsecure-service-js/blob/release/3.0.0/package.json#L16) library where typings properly exported from library.

**Comment by bernardbr** [comment]
Hello @pashchuk! We released version 2.2.0 with the d.ts file.
