### ISSUE TITLE
NextJS build fails with paybyrd library import

### ISSUE THREAD

**Issue by pashchuk** [paybyrd/card-collect-js#8]
Dear PayByrd team.

As your customers we often working with libraries you are providing to us. But there are some tech issues while working with them.  
Right now we are moving to the NextJS along with Server Side Rendering (SSR) capabilities to better adopt our application for crawling bots and optimise rendering speed for not so performant devices.  

We have faced issue while trying to build the application with ssr mode on - it works fine with ton of other packages but immediately fails once we add usage of card-collect. 

In general error looks like this one:

```
$ yarn build

yarn run v1.22.17
$ next build
- info Linting and checking validity of types
- info Creating an optimized production build
- info Compiled successfully
- info Collecting page data .ReferenceError: document is not defined
    at A.exports [as insertStyleElement] (/project-path/.next/server/chunks/965.js:564:21)
    at A.exports [as domAPI] (/project-path/.next/server/chunks/965.js:576:23)
    ...

> Build error occurred
Error: Failed to collect page data for /
    at /project-path/node_modules/next/dist/build/utils.js:1156:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I suspect there is something wrong with [css import into module](https://github.com/paybyrd/card-collect-js/blob/2.2.0/src/index.ts#L11), where bundler generating js code, which is trying to insert css style directly using `document` object - which is not defined on the sever side if you are using SSR mode.

Other packages like Stripe works just fine.   

Our developer has created a small repro in advance to save your time - which you can use to identify the issue.  
[Please find it here on Github](https://github.com/Krombik/paybyrd-next-issue)
Maybe we fix bundler somehow or split *.js and *.css into separate bundles so no document insert will stop your library from using in in SSR mode?

**Comment by paulocesarpcfj** [comment]
Hi!! I hope you are doing great 😄.

I was checking this issue and since our lib was built in VanillaJS we have to use handlers from the document to access HTML elements to perform changes, listeners and other stuff to make everything work. I took a look in the code you provided in the issue and I fixed it to make it work properly attending to VanillaJS, but I don't have privileges to create a PR in there, so I am sending the snippet here with the working code. The only difference is that since NextJS is SSR, we should wait for the first render of the component and then we are able to import Paybyrd library that now will have access to the DOM normally and it will work as expected. Let me know if you have any other questions! Thanks!

```
import { useEffect, useState } from "react";

const Home = () => {
  const [cc, setCardCollect] = useState(null);

  const handleSubmit = () => {
    cc.cardCollect_submit()
      .then(({ status, data }) => console.log("Success:", status, data)) // Handle paybyrd's response here
      .catch((error) => console.log("Error:", error)); // Handle any errors here
  };

  const handleFieldChange = ({ fieldId, element, error, isValid }) => {
    console.log(fieldId, element, error, isValid);
  };

  useEffect(() => {
    const setup = async () => {
      const CardCollect = await import("@paybyrd/card-collect/dist/cardCollect-web");

      if (!cc) {
        const cardCollect = await CardCollect.default({
          displayErrors: true, // Optional. It will display error messages automatically without any extra configurations
          onFieldChange: handleFieldChange, // Optional. It will retrieve an object with metadata to perform extra validations
          validateOnChange: false, // Optional [default false]. It will validate on change even before form submission
          displayHelpIcons: true, // Optional [default false]. It will display the CVV and Expiry Date placeholder icons inside the input
        });
        setCardCollect(cardCollect);
      }
    };

    setup();
  }, []);

  return (
    <div id="cardCollect">
      <div id="cc-holder" className="form-field" data-placeholder="Card Holder"></div>
      <div id="cc-number" className="form-field" data-placeholder="Card Number"></div>
      <div className="form-field-group">
        <div id="cc-expiration-date" className="form-field" data-placeholder="MM/YY"></div>
        <div id="cc-cvc" className="form-field" data-placeholder="CVV"></div>
      </div>
      <button className="form-button" onClick={handleSubmit}>
        Submit
      </button>
    </div>
  );
};

export default Home;
```
